DECLARE @max_iyperiod INT;
SET @max_iyperiod = 201708
/*UPDATE ODM.COST_OACCO_DEPART_GET_MAP
SET CDEPT_ID = '101'
WHERE O_ACCO_CODE IN (
		SELECT O_ACCO_CODE
		FROM ODM.COST_OUT_ACCOUNT
		WHERE O_ACCO_NAME IN ('翌景大厦房租', '数据中心房租')
	);*/
delete ODM.COST_OACCO_DEPART_GET_MAP  WHERE O_ACCO_CODE IN (
		SELECT O_ACCO_CODE
		FROM ODM.COST_OUT_ACCOUNT
		WHERE O_ACCO_NAME IN ('翌景大厦房租', '数据中心房租')
	);
insert into odm.COST_OACCO_DEPART_GET_MAP (O_ACCO_CODE,CDEPT_ID) values('7','101');
insert into odm.COST_OACCO_DEPART_GET_MAP (O_ACCO_CODE,CDEPT_ID) values('8','304');
insert into odm.COST_OACCO_DEPART_GET_MAP (O_ACCO_CODE,CDEPT_ID) values('8','101');
DELETE FROM odm.COST_ALLOC_VALUE
WHERE IYPERIOD >= @max_iyperiod;
DELETE FROM odm.COST_PUB_EXPENSE
WHERE IYPERIOD >= @max_iyperiod;
DELETE FROM odm.COST_DEPT_FULL_COSTING
WHERE IYPERIOD >= @max_iyperiod;
DELETE FROM odm.COST_FUNC_DEPT_FULL_COSTING
WHERE IYPERIOD >= @max_iyperiod;
DELETE FROM odm.COST_COST_DETAILS
WHERE IYPERIOD = @max_iyperiod

--insert into odm.COST_OACCO_DEPART_GET_MAP (O_ACCO_CODE,CDEPT_ID) values('8','304')