CREATE OR REPLACE TRIGGER "TEST_STUDY_0001_T"  
  BEFORE INSERT ON TEST_STUDY_0001  
  REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW  
DECLARE  
BEGIN  
  SELECT TEST_STUDY_0001_S.NEXTVAL INTO :NEW.ID FROM DUAL;  
END TEST_STUDY_0001_T;  
